# Generated by Django 4.1.2 on 2022-10-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
